$("#menu").click(function(){
  $("#menu").toggleClass("animate");
  $("#menuBar1").toggleClass("animate");
  $("#menuBar2").toggleClass("animate");
  $("#menuBar3").toggleClass("animate");
  $("#toggleNav").toggleClass("animate");
  $("nav").toggleClass("animate");
  $("#logo").toggleClass("animate");
  $(".project").toggleClass("animate");
});
